#!/bin/bash
#how to declare an array
# #!/bin/bash
declare -a my_array
my_array=(1 2 3 4 5)
echo ${my_array[0]}
echo ${my_array[1]}
echo ${my_array[2]} 
#print all elements of an array
#!/bin/bash
declare -a my_array
my_array=(1 2 3 4 5)
for i in "${my_array[@]}"
do
echo $i
# how to get the length of an array
#!/bin/bash
declare -a my_array
my_array=(1 2 3 4 5)
length=${#my_array[@]}
echo $length
how to get range of elements in an array
#!/bin/bash
declare -a my_array
my_array=(1 2 3 4 5)
echo ${my_array[@]:1:3}
how to update an array
#!/bin/bash
declare -a my_array
my_array=(1 2 3 4 5)
my_array[0]=10
echo ${my_array[@]}
# array key-value pairs
# #!/bin/bash
declare -A my_array
my_array=(["name"]="John" ["age"]=25 ["city"]="New York")
echo ${my_array["name"]}
echo ${my_array["age"]}
echo ${my_array["city"]}
